version: 2.1
jobs:
  unit-test:
    docker:
      - image: python:3.7.9
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: black --check .
      - run: python3 test_unit.py
  integration-test:
    docker:
      - image: docker:19
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: apk add make bash git docker-compose
      - checkout
      - run: make docker-test
workflows:
  version: 2
  test:
    jobs:
      - unit-test
      - integration-test
